# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbf1febb18a4a71c312043f8d4c9b52c9771f024d336bf198e21f0a8d9f27e17dec1425b7487b2d158ea9afdc9f8bfd0506fb3f7f15acfa8646f6513187a1914

test:
  secret_key_base: d515d89ecfdacaa374edd4a0e2e58cd7d815588b0665f84eafdfba1bed5729a30b71f464f7c720eca783e658cd39cf07e349564370da020f7c557adbf6bb608d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
